name: Publish Contracts
on:
  push:
    paths:
      - "packages/contracts/**"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - run: pnpm install
      - run: pnpm -F @allecto-app/contracts build
      - run: npm publish --workspace packages/contracts
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
